name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_extract.py
      id: test_extract-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: test_transform.py
      id: test_transform-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: test_load.py
      id: test_load-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_EXTRACT-PY_RESULTS: "${{steps.test_extract-py.outputs.result}}"
        TEST_TRANSFORM-PY_RESULTS: "${{steps.test_transform-py.outputs.result}}"
        TEST_LOAD-PY_RESULTS: "${{steps.test_load-py.outputs.result}}"
      with:
        runners: test_extract-py,test_transform-py,test_load-py
