name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Extract-Test
      id: extract-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Extract-Test
        setup-command: pip install -r requirements.txt
        command: pytest test/test_extract
        timeout: 10
        max-score: 10
    - name: Transform-Test
      id: transform-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Transform-Test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_transform
        timeout: 10
        max-score: 10
    - name: Load-Test
      id: load-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Load-Test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_load
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXTRACT-TEST_RESULTS: "${{steps.extract-test.outputs.result}}"
        TRANSFORM-TEST_RESULTS: "${{steps.transform-test.outputs.result}}"
        LOAD-TEST_RESULTS: "${{steps.load-test.outputs.result}}"
      with:
        runners: extract-test,transform-test,load-test
